---
title: "015_LEPAS_Phyto_GAMM_Figures_MasterScript_20200312"
author: "DRO"
date: "3/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(mgcv)
library(scales)
library(MuMIn)
library(car)

# Western Basin
wb_sp <- read.csv("~/Documents/OSU/Projects/LEPAS_Briland/Data/Phytoplankton/LEPAS_Phytoplankton_WesternB_Spring_Updated_20200625.csv")
wb_es <- read.csv("~/Documents/OSU/Projects/LEPAS_Briland/Data/Phytoplankton/LEPAS_Phytoplankton_WesternB_EarlySummer_Updated_20200625.csv")
wb_ls <- read.csv("~/Documents/OSU/Projects/LEPAS_Briland/Data/Phytoplankton/LEPAS_Phytoplankton_WesternB_LateSummer_Updated_20200625.csv")

# Central Basin
cb_sp <- read.csv("~/Documents/OSU/Projects/LEPAS_Briland/Data/Phytoplankton/LEPAS_Phytoplankton_CentralB_Spring_Updated_20200625.csv")
cb_es <- read.csv("~/Documents/OSU/Projects/LEPAS_Briland/Data/Phytoplankton/LEPAS_Phytoplankton_CentralB_EarlySummer_Updated_20200625.csv")
cb_ls <- read.csv("~/Documents/OSU/Projects/LEPAS_Briland/Data/Phytoplankton/LEPAS_Phytoplankton_CentralB_LateSummer_Updated_20200625.csv")

```


Gaussian GAMM fits
```{r}

plotFunc <- function(dat1,dat2,dat3,taxon){
  
  taxon1 <- dat1[,taxon]
  taxon2 <- dat2[,taxon]
  taxon3 <- dat3[,taxon]

  fixDats <- function(dats,tax){
    dats %>% 
      mutate(PresAbs = ifelse(tax > 0, 1, 0),
             Sample_date = as.POSIXct(paste(Year,substr(Sample_ID,5,6),substr(Sample_ID,7,8),sep="-")),
             Sample_date = as.Date(Sample_date)) %>% 
      arrange(Sample_date) %>% 
      mutate(Time = decimal_date(Sample_date)) %>% 
      select(Sample_ID:DOY,Time,Event,everything())
  }
  
  # Subset out nonzero data.
  nz1 <- fixDats(dat1,taxon1) %>% mutate(taxon1 = taxon1) %>% filter(taxon1 > 0)
  nz2 <- fixDats(dat2,taxon2) %>% mutate(taxon2 = taxon2) %>% filter(taxon2 > 0)
  nz3 <- fixDats(dat3,taxon3) %>% mutate(taxon3 = taxon3) %>% filter(taxon3 > 0)

  points1 <- nz1 %>% 
    select(x=Time, y=taxon1, Site_consolidated)
  points2 <- nz2 %>% 
    select(x=Time, y=taxon2, Site_consolidated)
  points3 <- nz3 %>% 
    select(x=Time, y=taxon3, Site_consolidated)
  
  # Three GAMMs for three seasons.
  mod1 <- gam(log(taxon1) ~ s(Time,k=8)+ s(DOY)+ s(Site_consolidated,bs="re"), data=nz1)
  mod2 <- gam(log(taxon2) ~ s(Time,k=8)+ s(DOY)+ s(Site_consolidated,bs="re"), data=nz2)
  mod3 <- gam(log(taxon3) ~ s(Time,k=8)+ s(DOY)+ s(Site_consolidated,bs="re"), data=nz3)

  # plot.gam() objects from which to pull data.
  pdf(NULL)
  dev.control(displaylist="enable")
  gplot1 <- plot(mod1, n=nrow(nz1))
  gplot2 <- plot(mod2, n=nrow(nz2))
  gplot3 <- plot(mod3, n=nrow(nz3))
  invisible(dev.off())
  
  # Data from plot.gam() objects above, needed for ggplots.
  PlotFit1 <- data.frame(x=gplot1[[1]]$x, y=gplot1[[1]]$fit, se=gplot1[[1]]$se) %>% 
    mutate(y.ts = exp(y+mean(predict(mod1))),
           y.lwr95 = exp(y-1.96*se+mean(predict(mod1))),
           y.uppr95 = exp(y+1.96*se+mean(predict(mod1))))
  PlotFit2 <- data.frame(x=gplot2[[1]]$x, y=gplot2[[1]]$fit, se=gplot2[[1]]$se) %>% 
    mutate(y.ts = exp(y+mean(predict(mod2))),
           y.lwr95 = exp(y-1.96*se+mean(predict(mod2))),
           y.uppr95 = exp(y+1.96*se+mean(predict(mod2))))
  PlotFit3 <- data.frame(x=gplot3[[1]]$x, y=gplot3[[1]]$fit, se=gplot3[[1]]$se) %>% 
    mutate(y.ts = exp(y+mean(predict(mod3))),
           y.lwr95 = exp(y-1.96*se+mean(predict(mod3))),
           y.uppr95 = exp(y+1.96*se+mean(predict(mod3))))

  # Plot with 3 GAMM curves.
  ggplot(PlotFit1, mapping=aes(x=x, y=y.ts))+
    geom_ribbon(mapping=aes(x=x, ymin=y.lwr95, ymax=y.uppr95), fill="limegreen", col="limegreen", 
                size=0.00, alpha=0.2)+
    geom_ribbon(PlotFit2, mapping=aes(x=x, ymin=y.lwr95, ymax=y.uppr95), fill="blue", col="blue",
                size=0.00, alpha=0.2)+
    geom_ribbon(PlotFit3, mapping=aes(x=x, ymin=y.lwr95, ymax=y.uppr95), fill="violet", col="violet",
                size=0.00, alpha=0.3)+
    geom_point(points1, mapping=aes(x=x, y=y), color="limegreen", alpha=0.35)+
    geom_point(points2, mapping=aes(x=x, y=y), color="blue", alpha=0.2)+
    geom_point(points3, mapping=aes(x=x, y=y), color="mediumorchid3", alpha=0.3)+
    geom_path(PlotFit1, mapping=aes(x=x, y=y.ts), col="limegreen", size=0.9)+
    geom_path(PlotFit2, mapping=aes(x=x, y=y.ts), col="blue", size=0.9)+
    geom_path(PlotFit3, mapping=aes(x=x, y=y.ts), col="mediumorchid3", size=0.9)+
    theme_classic()+
    xlim(1995,2015)+
    labs(x="", y="", size=0.9)+
    scale_y_log10(breaks=trans_breaks("log10", function(x) 10^x, n=5),
                  labels=trans_format("log10", math_format(10^.x)), 
                  limits=c(1e-6,1e5))+
    annotation_logticks()+
    theme(axis.title = element_text(size = 26), 
          axis.text = element_text(size = 26))+
    theme(plot.title = element_text(size=20, hjust=0.9),
          text = element_text(family="Times", size=0.9))
  
}

pdf("~/Documents/OSU/Projects/LEPAS_Briland/Figures/SuppFigs/LEPAS_CB_Diatoms_Overlay_GAMM_20200421.pdf", 
    height = 5, width = 8)

plotFunc(cb_sp,cb_es,cb_ls, taxon="Diatom")

dev.off()

```


Binomial/logistic GAMM fits.
```{r}


plotFunc2 <- function(dat1,dat2,dat3,taxon){
  
  taxon1 <- dat1[,taxon]
  taxon2 <- dat2[,taxon]
  taxon3 <- dat3[,taxon]

  fixDats <- function(dats,tax){
    dats %>% 
      mutate(PresAbs = ifelse(tax > 0, 1, 0),
             Sample_date = as.POSIXct(paste(Year,substr(Sample_ID,5,6),substr(Sample_ID,7,8),sep="-")),
             Sample_date = as.Date(Sample_date)) %>% 
      arrange(Sample_date) %>% 
      mutate(Time = decimal_date(Sample_date)) %>% 
      select(Sample_ID:DOY,Time,Event,everything())
  }
  
  # Subset out nonzero data.
  pa1 <- fixDats(dat1,taxon1) %>% mutate(taxon1 = taxon1)
  pa2 <- fixDats(dat2,taxon2) %>% mutate(taxon2 = taxon2)
  pa3 <- fixDats(dat3,taxon3) %>% mutate(taxon3 = taxon3)
  
  points1 <- data.frame(Time = pa1$Time,
                        y = pa1$PresAbs,
                        Site_consolidated = pa1$Site_consolidated)
  points2 <- data.frame(Time = pa2$Time,
                        y = pa2$PresAbs,
                        Site_consolidated = pa2$Site_consolidated)
  points3 <- data.frame(Time = pa3$Time,
                        y = pa3$PresAbs,
                        Site_consolidated = pa3$Site_consolidated)
  
  # Three GAMMs for three seasons.
  # plot.gam() objects from which to pull data.
  pdf(NULL)
  dev.control(displaylist="enable")
  if(length(pa1$PresAbs[pa1$PresAbs==0]) >= 20){
    mod1 <- gam(PresAbs ~ s(Time,k=8)+ s(DOY)+ s(Site_consolidated,bs="re"), family=binomial("logit"), data=pa1)
    gplot1 <- plot(mod1)
    PlotFit1 <- data.frame(x=gplot1[[1]]$x, y=gplot1[[1]]$fit, se=gplot1[[1]]$se) %>% 
      mutate(y.ts = exp(y+mean(predict(mod1)))/(1+exp(y+mean(predict(mod1)))),
             y.lwr95 = exp(y-1.96*se+mean(predict(mod1)))/(1+exp(y-1.96*se+mean(predict(mod1)))),
             y.uppr95 = exp(y+1.96*se+mean(predict(mod1)))/(1+exp(y+1.96*se+mean(predict(mod1)))))
    size1 <- 0.9
  }
  else{
    PlotFit1 <- data.frame(x=1995:2015, y=rep(0,21), y.ts=rep(0,21), 
                           y.lwr95=rep(0,21), y.uppr95=rep(0,21))
    size1 <- 0.00
  }
  if(length(pa2$PresAbs[pa2$PresAbs==0]) >= 20){
    mod2 <- gam(PresAbs ~ s(Time,k=10)+ s(DOY)+ s(Site_consolidated,bs="re"), family=binomial("logit"), data=pa2)
    gplot2 <- plot(mod2)
    PlotFit2 <- data.frame(x=gplot2[[1]]$x, y=gplot2[[1]]$fit, se=gplot2[[1]]$se) %>% 
      mutate(y.ts = exp(y+mean(predict(mod2)))/(1+exp(y+mean(predict(mod2)))),
             y.lwr95 = exp(y-1.96*se+mean(predict(mod2)))/(1+exp(y-1.96*se+mean(predict(mod2)))),
             y.uppr95 = exp(y+1.96*se+mean(predict(mod2)))/(1+exp(y+1.96*se+mean(predict(mod2)))))
    size2 <- 0.9
  }
  else{
    PlotFit2 <- data.frame(x=1995:2015, y=rep(0,21), y.ts=rep(0,21),
                           y.lwr95=rep(0,21), y.uppr95=rep(0,21))
    size2 <- 0.00
  }
  if(length(pa3$PresAbs[pa3$PresAbs==0]) >= 20){
    mod3 <- gam(PresAbs ~ s(Time,k=8)+ s(Site_consolidated,bs="re"), family=binomial("logit"), data=pa3)
    gplot3 <- plot(mod3)
    PlotFit3 <- data.frame(x=gplot3[[1]]$x, y=gplot3[[1]]$fit, se=gplot3[[1]]$se) %>% 
      mutate(y.ts = exp(y+mean(predict(mod3)))/(1+exp(y+mean(predict(mod3)))),
             y.lwr95 = exp(y-1.96*se+mean(predict(mod3)))/(1+exp(y-1.96*se+mean(predict(mod3)))),
             y.uppr95 = exp(y+1.96*se+mean(predict(mod3)))/(1+exp(y+1.96*se+mean(predict(mod3)))))
    size3 <- 0.9
  }
  else{
    PlotFit3 <- data.frame(x=1995:2015, y=rep(0,21), y.ts=rep(0,21), 
                           y.lwr95=rep(0,21), y.uppr95=rep(0,21))
    size3 <- 0.00
  }
  invisible(dev.off())

  # Plot with 3 GAMM curves.
  ggplot()+
    xlim(1995,2015)+
    ylim(-0.2,1.2)+
    theme_classic()+
    # geom_ribbon(PlotFit1, mapping=aes(x=x, ymin=y.lwr95, ymax=y.uppr95), fill="limegreen", col="limegreen",
    #             size=0.00, alpha=0.2)+
    # geom_ribbon(PlotFit2, mapping=aes(x=x, ymin=y.lwr95, ymax=y.uppr95), fill="blue", col="blue",
    #             size=0.00, alpha=0.2)+
    # geom_ribbon(PlotFit3, mapping=aes(x=x, ymin=y.lwr95, ymax=y.uppr95), fill="violet", col="violet",
    #             size=0.00, alpha=0.3)+
    geom_point(points1, mapping=aes(x=Time, y=y), color="limegreen", alpha=0.35,
               position=position_jitter(width=0.25, height=0.02), size=0.9)+
    geom_point(points2, mapping=aes(x=Time, y=y), col="blue", alpha=0.2,
               position=position_jitter(width=0.25, height=0.02), size=0.9)+
    geom_point(points3, mapping=aes(x=Time, y=y), col="mediumorchid3", alpha=0.3,
               position=position_jitter(width=0.25, height=0.02), size=0.9)+
    geom_path(PlotFit1, mapping=aes(x=x, y=y.ts), col="limegreen", size=size1)+
    geom_path(PlotFit2, mapping=aes(x=x, y=y.ts), col="blue", size=size2)+
    geom_path(PlotFit3, mapping=aes(x=x, y=y.ts), col="mediumorchid3", size=size3)+
    labs(x="", y=expression("P"), size=0.9)+
    theme(axis.title = element_text(size = 26), 
          axis.text = element_text(size = 26),
          axis.title.y = element_text(vjust = 4), 
          plot.title = element_text(size=20, hjust=0.9),
          text = element_text(family="Times", size=0.9),
          plot.margin=unit(c(0.1,0.6,0.1,0.65), "cm"))+
    scale_y_continuous(breaks=c(0,1))
  
}

pdf("~/Documents/OSU/Projects/LEPAS_Briland/Figures/TotalPP/LEPAS_TotalPP_WB_Overlay_LOGISTIC_20200311.pdf", 
    height = 1.8, width = 7.36, family="Times")

plotFunc2(cb_sp,cb_es,cb_ls,taxon="Diatom")

dev.off()

```




